language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - libhdf5-serial-dev
before_install:
    - pip install coveralls
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
install:
    - python setup.py install
script:
    - py.test /moldynplot/test
after_success:
    - coveralls
