language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - libhdf5-serial-dev
before_install:
    - pip install coveralls
    - pip install pytest pytest-cov
install:
    - pip install -r requirements.txt
before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/..
script:
    - py.test
after_success:
    - coveralls
