language: python
cache: pip
python:
    - "2.7"
addons:
    apt:
        packages:
            - gfortran
            - libhdf5-serial-dev
            - liblapack-dev
before_install:
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install h5py
    - pip install ipython
    - pip install matplotlib
    - pip install pandas
    - pip install pyyaml
    - pip install scipy
    - pip install scikit-learn
install:
    - python setup.py install
script:
    - cd moldynplot/test
    - py.test --cov .. --cov-report=term-missing
after_success:
    - pwd
    - ls -al
    - ls -al ..
    - ls -al ../..
    - coveralls
