language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - libhdf5-serial-dev
before_install:
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install h5py
    - pip install ipython
    - pip install matplotlib
    - pip install pandas
install:
    - python setup.py install
script:
    - cd moldynplot/test/
    - py.test
after_success:
    - coveralls
